apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"java-app:latest","namespace":"app-deploy"},"fieldPath":"spec.template.spec.containers[?(@.name==\"java-app\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2023-06-15T14:26:03Z"
  generation: 2
  labels:
    app: java-app
    app.kubernetes.io/component: java-app
    app.kubernetes.io/instance: java-app
    app.kubernetes.io/name: java-app
  name: java-app
  namespace: app-deploy
  resourceVersion: "1357986"
  uid: 3e044cc7-1c55-4292-8d70-0e6ba17a0eec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: java-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: java-app
    spec:
      containers:
      - image: docker.io/vito490/simple-java-endpoint@sha256:7fe9f8162458e7f5e80bab28ba8b1ca7a9f3c2b0d183617cca6d041c6c38c51f
        imagePullPolicy: IfNotPresent
        name: java-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
